spring:
  application:
    name: Config-Prod
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
